### PR TITLE
Viewability improvements

### PR DESCRIPTION
**Pull request by aintgoin2goa**
* Better data structure
* Sends data every 10 seconds and on unload (if beacons are supported)
* checks if user is interacting with page or not

### CODE REVIEW

**Comment by commuterjoy** [comment]
> Sends data every 10 seconds

I quite liked the localStorage thing. Little worried that our beacon costs are capped at 8 million per month. So don't want to whack it with thousands of ad calls until we can see how the alpha is going to effect costs.

**Comment by commuterjoy** [comment]
Would be really good to sit with @spriggsha for a bit and test this. It really matters that we are collecting good data here. We are trying to prove a point that we can be trusted :)

**Comment by aintgoin2goa** [comment]
Fair enough, I can remove the 10 second thing - was concerned that having a system where we admit that a whole bunch of data might never get sent might not engender trust, either.

If I do that can I merge?

**Comment by commuterjoy** [comment]
merge, but i've still not go around to looking through the code - there's quite a lot of it. will do that tomorrow.

can you take the init out of the main.js for now?

**Comment by aintgoin2goa** [comment]
ok, have merged without the init.  Also haven't done a release yet

**Comment by aintgoin2goa** [comment]
Also, there's more changes to the Algorithm to come - Robin has pointed out that I need to take the position of the window on the screen into accout

**Pull request merged**
