### PR TITLE
Scroll depth tracking

### PR DESCRIPTION
**Pull request by quarterto**
/cc @commuterjoy

### CODE REVIEW

**Comment by quarterto** [comment]
Tests would help...

**Comment by commuterjoy** [comment]
:+1: nice.

We also talked about adding word count and the number of seconds since page load to the event detail.

**Comment by quarterto** [comment]
@commuterjoy added that stuff

**Comment by commuterjoy** [comment]
@quarterto Looks good. Merge it and release it.

I added this fc01c3c - i think 'seconds' is a more usable metric for people to understand, and I think words per minute may be interesting to plot as time and word count on their own are meaningless (Eg, more words will always take longer to read, so we are interested in the ratio).

**Pull request merged**
