### PR TITLE
recognise new streams

### PR DESCRIPTION
**Pull request by wheresrhys**
@matthew-andrews Please add to this if I've missed any, or merge if correct

### CODE REVIEW

**Comment by matthew-andrews** [comment]
think we need to ask mr @commuterjoy very nicely to fix master :-)

**Comment by commuterjoy** [comment]
ok, I merged with a fixed master.

**Comment by commuterjoy** [comment]
'cos you asked nicely :)

**Comment by matthew-andrews** [comment]
^_^

**Pull request merged**
